name: Documenter
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  Documenter:
    name: Build Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Document
        run: |
                using Pkg
                Pkg.activate(".")
                Pkg.add("Documenter")
                include("make.jl")
        shell: julia --color=yes {0}
