name: Documenter
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  Documenter:
    name: Build Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Document
        run: |
                julia --color=yes -e '
                        using Pkg;
                        Pkg.activate(".")
                        Pkg.add("Documenter")
                        include("make.jl")
                        '
        env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
